"""Add configuration table

Revision ID: 90497b1af6ea
Revises: cd045326033d
Create Date: 2024-06-20 16:11:08.841569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90497b1af6ea'
down_revision = 'cd045326033d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_dice_count', sa.Integer(), nullable=False),
    sa.Column('max_games_per_session', sa.Integer(), nullable=False),
    sa.Column('max_sessions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('configuration')
    # ### end Alembic commands ###
